# fly.toml app configuration file generated for todox-app on 2026-07-11T23:44:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todox-app'
primary_region = 'ams'

[build]
[env]
  DB_PATH = '/data/todos.db'
  PORT = '8080'

[[mounts]]
  source = 'todox_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
